---
title: "1_Practical"
author: "Ryan Greenup 17805315"
date: "12 March 2019"
output:
  html_document:
    code_folding: hide
    keep_md: yes
    theme: flatly
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document: 
    toc: yes
always_allow_html: yes
  ##Shiny can be good but {.tabset} will be more compatible with PDF
    ##but you can submit HTML in turnitin so it doesn't really matter.
    
 ##It is rare that you will want to use a floating toc with {.tabset}
    ##If a floating toc is used in the document only use {.tabset} on more or less copy/pasted 
        #sections with different datasets
    ##Otherwise use {.tabsets} instead of TOC or TOC instead of {.tabsets}, one or the other though.
---

Refer to [Stack](https://stackoverflow.com/questions/25824795/how-to-combine-two-rmarkdown-rmd-files-into-a-single-output)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if(require('pacman')){
  library('pacman')
}else{
  install.packages('pacman')
  library('pacman')
}

pacman::p_load(ggplot2, rmarkdown, shiny, ISLR, class, BiocManager, corrplot, plotly)
  #Mass isn't available for R 3.5...
```

This is only going to work if i pull the setup part out ouf it

```{r child = '01_Practical.Rmd'}
```

```{r child = '02_Practical.Rmd'}
```

```{r child = '03_Practical.Rmd'}
```

```{r child = '04_Practical.Rmd'}
```

```{r child = '05_Practical.Rmd'}
```

```{r child = '06_Practical.Rmd'}
```

```{r child = '07_Practical.Rmd'}
```

```{r child = '08_Practical.Rmd'}
```

```{r child = '09_Practical.Rmd'}
```

```{r child = '10_Practical.Rmd'}
```

```{r child = '11_Practical.Rmd'}
```

```{r child = '12_Practical.Rmd'}
```

```{r child = '13_Practical.Rmd'}
```